---
title: "Knitr tips"
author: "Michael Friendly"
date: "5/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This document records a few tips and tricks I've learned in using `knitr`, `pandoc` and other `R` tools
for writing articles and other documents using R markdown.

## YAML tips

A basic requirement for an R markdown `.Rmd` file is a header in YAML format, essentially a list of
tags and values used when formatting the document.  This is what I got when I first created this document
in R Studio, using `File -> New File -> R markdown`, where my name had already been recorded.

```
---
title: "Knitr tips"
author: "Michael Friendly"
date: "5/13/2020"
output: html_document
---
```

Now, this might be OK, but what if I want the date to be updated automatically for the current version?
This is where the power of knitr and R combine to make this easier.  Just use an "`r expression`"
in the `date:` field.  

```
---
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---
```
The key insight here is that most fields in a YAML header processed by `knitr`
and `pandoc` are now **computable** using an "`r expression`".

## Bibliographies

I'm a longtime LaTeX user, so all my bibliographic information are in a collection of
BibTeX `.bib` files. 

```
bibliography:
  - "../../../localtexmf/bibtex/bib/graphics.bib"
  - "../../../localtexmf/bibtex/bib/Rpackages.bib"
  - "../../../localtexmf/bibtex/bib/statistics.bib"
  - "../../../localtexmf/bibtex/bib/timeref.bib"
```

Now that I understood the power of "`r expression`" in YAML ...

```
bibliography:
  - "`r system('kpsewhich graphics.bib', intern=TRUE)`"
  - "`r system('kpsewhich statistics.bib', intern=TRUE)`"
  - "`r system('kpsewhich timeref.bib', intern=TRUE)`"
---
```

Those who use Zotero can now accomplish something similar with the ... package.


